base/Dockerfile.rhel
We want to work against both microdnf and yum base images.
=> Tolerate being used against a yum base image

base/Dockerfile.rhel
It's 403kb uncompressed and it makes backup/log management easier.
=> Add rsync back into the base image for better debugging

base/Dockerfile.rhel
bashlex doesn't like them. It won't parse when OCP automation goes through mangling things. I don't know why, and it's easier to just change this.
=> base/Dockerfile.rhel: don't use double brackets.

base/Dockerfile, base/Dockerfile.centos7, base/Dockerfile.rhel, base/Dockerfile.rhel7
Ensure yum install fails if a package is missing.
=> base/*: Set skip_missing_names_on_install=0 in /etc/yum.conf

egress/dns-proxy/Dockerfile
Move to haproxy 2.x which is packaged here:
https://pkgs.devel.redhat.com/cgit/rpms/haproxy/log/?h=rhaos-4.4-rhel-7
=> egress/dns-proxy: switch to haproxy 2.x

base/Dockerfile, base/Dockerfile.centos7, base/Dockerfile.rhel, base/Dockerfile.rhel7
`iproute` package provides `ss` tool. KAS, KCM (and KS) are using `ss` tool to wait for port to be available before running the app.
Given the code is already merged for KCM and KAS, the package might have already been in base image as a transitive before. There are now reported case where the `ss` command is missing https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/1276818504464470016
/cc @smarterclayton
=> Add iproute package to get `ss` tool for port wait

base/Dockerfile.rhel8
It has to point to Dockerfile.rhel not Dockerfile.rhel7:
https://github.com/openshift/release/blob/a15012e5874b8b75b3609c1143ae7a583899e5b0/ci-operator/config/openshift/images/openshift-images-release-4.6.yaml#L29
=> Fix link for rhel8 Dockerfile

base/Dockerfile.rhel
ubi7 had python2 available for direct user consumption by default. ubi8 dropped this and instead has python3 installed, but only available internally for utilities like yum. By explicitly installing it here, we hope to satisfy the older assumptions layered images have on the openshift base.
Layered images that have python2 specific code will need to modify that code (recommended) or explicitly install python2 in their Dockerfile and use `alternatives` to make it their default.
=> Bug 1873414: Install python3 in ubi8 base to emulate ubi7

base/Dockerfile.rhel
This is an intermediate step as we migrate OCP 4.6 to a rhel8
base. During this work, the console downloader was migrated
to python3, but python3 was previously unavailable in the ocp
base image.
=> Make python3 available in ubi7 base image

pod/pod.go
The purpose of this pull request is to add handling the SIGCHLD signal and proper reaping of the zombie processes to the `pod` binary.
This is to avoid exhaustion of the process table slots in some long running scenarios and to keep the behavior of pods consistent with the vanilla kubernetes distribution, when using [shareProcessNamespace: true](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/).
The default configuration of the cri-o deployed by Openshift/OKD (version 4) specifies the `pause_command = "/usr/bin/pod"`. This means that when the user spawns a pod with `shareProcessNamespace: true`, the pod binary will be launched as the init process in the pod's pid namespace. If one of the containers in that pod has an exec readiness probe configured, that …
=> Bug 1875946: Pod process container does not correctly reap zombie process with shareProcessNamespace: true

base/Dockerfile.rhel
RHEL 8 bind-utils depends on libmaxminddb (instead of GeoIP) which has
weak deps on the geolite2 databases, which end up bloating all of OpenShift.
=> Bug 1881494: base: do not install weak deps

base/Dockerfile.rhel
OCP 4.6 uses golang 1.15. 1.15 has deprecated the behavior of
treating the CommonName field on X.509 certificates as a
host name when no Subject Alternative Names are present.
https://golang.google.cn/doc/go1.15#commonname
Additional context:  https://coreos.slack.com/archives/CEKNRGF25/p1600867749007700
=> Bug 1883690: Enable x509 common name matching

base/Dockerfile.rhel
Updating openshift-enterprise-base builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-base.yml
=> Updating openshift-enterprise-base builder & base images to be consistent with ART

pod/Dockerfile.rhel
Updating openshift-enterprise-pod builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-pod.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating openshift-enterprise-pod builder & base images to be consistent with ART

egress/dns-proxy/Dockerfile
Updating openshift-enterprise-egress-dns-proxy builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-egress-dns-proxy.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating openshift-enterprise-egress-dns-proxy builder & base images to be consistent with ART

egress/http-proxy/Dockerfile
Updating ose-egress-http-proxy builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/ose-egress-http-proxy.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating ose-egress-http-proxy builder & base images to be consistent with ART

egress/dns-proxy/Dockerfile
This reverts commit 9d0f10cc5272b06adc303f669c20c98575da08e6, reversing
changes made to 791e631ca350e8093c6d916ff7aaaa4d13d9cd52.
haproxy-2.2.4 will not allow us to disable HTX anymore which means
client/servers will always get down-cased headers. As this may break
customers upgrading from OpenShift 4.6 => 4.7 we plan to add an API in
4.7 that will allow customers to specify case adjustment for various
routes. With that knob in place we will target 2.2.x for OpenShift 4.8
which is captured in this enhancement proposal:
https://github.com/openshift/enhancements/pull/550
PR that reverts the router to haproxy20:
https://github.com/openshift/router/pull/226
Related tickets:
- https://issues.redhat.com/browse/NE-426
- https://issues.redhat.com/browse/NE-473
=> Revert "Merge pull request #52 from jupierce/bump_haproxy"

egress/router/Dockerfile
Side effect of the rhel 8 transition.
`registry.svc.ci.openshift.org/ocp/4.5:base` includes iptables but `registry.svc.ci.openshift.org/ocp/4.6:base` does not, so let's install it so the egress-router can work again.
https://bugzilla.redhat.com/show_bug.cgi?id=1896170 for more context.
=> Bug 1896170: Egress router: Add iptables package to Dockerfile

egress/OWNERS, ipfailover/OWNERS
Copy relevant owners over from https://github.com/openshift/cluster-ingress-operator/blob/master/OWNERS to the Network Edge maintained components in this repo.
=> Update owners for Net Edge components

base/Dockerfile.rhel
Golang 1.12 changed to use MADV_FREE. MADV_FREE is somewhat faster than MADV_DONTNEED; however, the kernel will not try and reclaim memory in golang processes until the system is memory constrained. Cloud servers can potentially page out executable caches, which can cause IOPS throttles. Since golang 1.16  will be changing the default to MADV_DONTNEED, we are going to enable the flag by default.
This patch is 1 of 2. We need a separate patch in MCO to enable the system daemons (Kubelet and Crio).
https://github.com/golang/go/issues/42330
=> Bug 1907924: enable madvdontneed for golang

ipfailover/keepalived/Dockerfile
Updating openshift-enterprise-keepalived-ipfailover builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/openshift-enterprise-keepalived-ipfailover.yml
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.
=> Updating openshift-enterprise-keepalived-ipfailover builder & base images to be consistent with ART

egress/dns-proxy/Dockerfile
Switch to haproxy22 package. This is a move from haproxy-2.0 series to haproxy-2.2 in OCP-4.8.
=> egress/dns-proxy: Switch to haproxy22

ipfailover/keepalived/tests/echoserver.py
Legacy __print__ statements are syntax errors in Python 3 but __print()__ function works as expected in both Python 2 and Python 3.
=> Use print() function in both Python 2 and Python 3

ipfailover/keepalived/Dockerfile, ipfailover/keepalived/iptables-scripts/ip6tables, ipfailover/keepalived/iptables-scripts/ip6tables-restore, ipfailover/keepalived/iptables-scripts/ip6tables-save, ipfailover/keepalived/iptables-scripts/iptables, ipfailover/keepalived/iptables-scripts/iptables-restore, ipfailover/keepalived/iptables-scripts/iptables-save
The registry.ci.openshift.org/ocp/4.8:base image that the
ipfailover-keepalived container is based on doesn't include iptables,
which keepalived needs. This patch uses the same technique that's used
in [openshift-sdn's](https://github.com/openshift/sdn) container images,
which is to utilize the host's iptables executable.
With this commit, the ipfailover-keepalived image will require that the
host filesystem is mounted at `/host` inside the container, although
it's possible that just mounting the host's `/usr/sbin` at
`/host/usr/sbin/` will work as well
=> Bug 1960035: Add iptables shims to ipfailover-keepalived image

egress/dns-proxy/Dockerfile
This partially reverts PR #95.
We are switching back to haproxy-2.2 as our performance analysis shows
there are performance degradations when compared to the haproxy-2.2
series.
=> Revert to haproxy22

ipfailover/keepalived/Dockerfile, ipfailover/keepalived/lib/failover-functions.sh, ipfailover/keepalived/makefile.test, ipfailover/keepalived/remove-failover.sh
Signed-off-by: Mohamed Mahmoud <mmahmoud@redhat.com>
In order to allow existing customers who are using OpenShift failover feature to different HA implementations, we need to remove all fail over configurations
=> Add a script to remove all failover configurations.

ipfailover/keepalived/lib/config-generators.sh
This allows to exclude specific VRRP ID's to prevent conflicts with cluster VIPs for ipfailover deployments in environments that require a high amount of virtual IP's.
=> Bug 2018188: VRRP ID conflict between keepalived-ipfailover and cluster VIPs

ipfailover/keepalived/lib/utils.sh
If the user does not specify a network interface, keepalived-ipfailover tries a few default names: "enp0s3", "enp0s8", and "eth1".  If the host uses predictable network interface names as assigned by systemd/udev and the host has a network interface in a PCI Express hotplug slot, then the network interface is given a name of the form "ens3", in which case none of these default names matches it; in this case, before this PR, keepalived-ipfailover would fail to start if the user didn't specify the name explicitly.
To increase the likelihood of success for the defaulting logic on hosts with PCI Express hotplug slots, this PR adds "ens3" to the end of the list of default network interface names that keepalived-ipfailover tries.
Because this PR only changes the defaulting logic and adds to the …
=> Bug 2062126: ipfailover: Autodetect the "ens3" NIC

base/Dockerfile.rhel9, egress/dns-proxy/Dockerfile
Need corresponding ART PRs like https://github.com/openshift/release/pull/35786 and/or https://github.com/openshift/ocp-build-data/pull/2491
Note: doesn't do anything for the egress-router, proxy, or ipfailover images yet because those aren't base images for anything else and can stay on rhel8 for a while. We just want the `base` image to also have a RHEL9 variant because other images use it via FROM.
Note 2: bumps RHEL8 egress-dns-proxy image to haproxy26 to match what is being built in dist-git for the rhaos-4.13-rhel-8 brew tag.
@frobware (FYI for the haproxy part)
=> Dockerfile: add RHEL9 base image dockerfile

base/Dockerfile.rhel9
There is a build error, `alternatives` does not understand what to do with python: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=50822467
=> rhel9 base image: Fix build failure

egress/dns-proxy/Dockerfile
Reverting from haproxy26 to haproxy22 due to regression finding in OCPBUGS-10003.
`egress/dns-proxy/Dockerfile`: Update to haproxy 22 RPM
**Note**: This will need to be timed with the `rhpkg push` and `rhpkg build`. Once the new haproxy RPM is pushed, then mirrored (takes up to 24 hours), builds for this repo will start failing (haproxy26 rpm will be removed) and this PR will need to be merged.
=> OCPBUGS-10003: Revert "bump RHEL8 egress-dns-proxy image to haproxy26"

egress/dns-proxy/egress-dns-proxy.sh
It should fix [OCPBUGS-11385](https://issues.redhat.com/browse/OCPBUGS-11385).
HAProxy `chroot` setting makes little sense when we are already containerized, but it makes the container require to be privileged, which lowers container security too much.
=> OCPBUGS-11385: Removed chroot setting

ipfailover/keepalived/lib/config-generators.sh
Should be explicitly set to the default of  99. THe following message appears in logs:
```
- Loading ip_vs module ...
- Checking if ip_vs module is available ...
ip_vs 172032 0
- Module ip_vs is loaded.
- check for iptables rule for keepalived multicast (224.0.0.18) ...
- Generating and writing config to /etc/keepalived/keepalived.conf
- Starting failover services ...
Sun Feb 11 14:55:44 2024: Starting Keepalived v2.1.5 (07/13,2020)
Sun Feb 11 14:55:44 2024: Running on Linux 4.18.0-372.80.1.el8_6.x86_64 #1 SMP Fri Nov 3 14:30:16 EDT 2023 (built for Linux 4.18.0)
Sun Feb 11 14:55:44 2024: Command line: '/usr/sbin/keepalived' '-n' '--log-console'
Sun Feb 11 14:55:44 2024: Opening file '/etc/keepalived/keepalived.conf'.
Sun Feb 11 14:55:44 2024: NOTICE: setting config option …
```
=> OCPBUGS-29593: Add "max_auto_priority" to keepalived configuration to remove NOTICE from logs

egress/dns-proxy/egress_dns_proxy_test.go, go.mod
This is an manual cherry-pick of https://github.com/openshift/images/pull/165. 
This is the same change as #165 except we set the version of Go in `go.mod` to 1.20 to match the expectations of OCP 4.15.
CI enabled by https://github.com/openshift/release/pull/51358.
=> [release-4.15] OCPBUGS-30413: update unit tests in egress/dns-proxy

egress/router/Dockerfile
Bump OpenShift 4.16, RHEL9, and replace iptables package with iptables-nft package for RHEL9
Replaces #157
=> OCPBUGS-24850: Bump OpenShift 4.16, RHEL9, and iptables package

base/Dockerfile.rhel9
This PR adds the sig-nfv repositories when CentOS stream is the base image
=> OKD-210: Add the sig-nfv repo in the CS9 base

base/Dockerfile.rhel9
The `tests` image (at least) depends on packages from sig-cloud and the rt repository when built on top of CS9 as base image.
=> OKD-210: Add sig-cloud repository and enable rt repository

base/Dockerfile.rhel9
openshift/driver-toolkit assumes this plugin for `config-manager` . Probably easiest to enable it for everyone.
=> Add dnf-plugins-core in scos to help with OCP image compat

base/Dockerfile.rhel9
The centos-openstack-zed package fails with a dependency on rabbitmq - the mirrorlist url returns a 404.
```
CentOS-9 - RabbitMQ 38                          135 kB/s | 124 kB     00:00
Errors during downloading metadata for repository 'centos-rabbitmq-38':
- Status code: 404 for https://mirrors.centos.org/metalink?repo=centos-messaging-sig-rabbitmq-38--stream&arch=x86_64&protocol=https,http (IP: 67.219.144.68)
```
Add in the rdo repos which provide the python dependency instead
=> OKD-40: Remove centos-openstack-zed and add in rdo repo to get python-cinderclient dependency

base/Dockerfile.rhel9
https://github.com/openshift/release/pull/52010 is the root cause of the error with not finding the mirror list. adding the openstack repo back.
=> OKD-40: Revert #179

egress/OWNERS
- `egress/OWNERS`: Add `Thealisyed` and `grzpiotrowski` to the approvers and reviewers
Both are members of the Network Ingress/DNS team maintaining this component.
=> NO-JIRA: egress: update OWNERS

ipfailover/keepalived/conf/settings.sh, ipfailover/keepalived/lib/config-generators.sh
Changes the default value for OPENSHIFT_HA_VRRP_ID_OFFSET to 10 instead of zero. This will help prevent collisions with VRRP advertisements that are using the same VRID.
=> OCPBUGS-48318: Change default value for OPENSHIFT_HA_VRRP_ID_OFFSET
